### register success/duplicate
POST http://127.0.0.1:8080/register
Content-Type: application/json

{
  "username": "zenpk",
  "password": "zenpk"
}

### login wrong password
POST http://127.0.0.1:8080/login
Content-Type: application/json

{
  "username": "zenpk",
  "password": "wrong"
}

### login success
POST http://127.0.0.1:8080/login
Content-Type: application/json

{
  "username": "zenpk",
  "password": "zenpk"
}

### token gen failure
POST http://127.0.0.1:8080/token-gen
Content-Type: application/json

{
  "appId": "abc",
  "token": "abc"
}

### token gen success
POST http://127.0.0.1:8080/token-gen
Content-Type: application/json

{
  "appId": "abc",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTg5OTIyNjksIm5iZiI6MTY4NzQ1NjI2OSwiaWF0IjoxNjg3NDU2MjY5LCJpZCI6Mn0.9VbUfmdrO_yAVNF2ut-kdHL48jcpAC4TrjZ7m-xciYg",
  "age": 10000,
  "data": "'name':'zenpk'"
}

### token check wrong
POST http://127.0.0.1:8080/token-check
Content-Type: application/json

{
  "appId": "abc",
  "token": "abc"
}

### token check wrong appId
POST http://127.0.0.1:8080/token-check
Content-Type: application/json

{
  "appId": "abcd",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjU0NDQ3OTIsIm5iZiI6MTY4OTQ0NDc5MiwiaWF0IjoxNjg5NDQ0NzkyLCJhcHBJZCI6ImFiYyIsImRhdGEiOiInbmFtZSc6J3plbnBrJyJ9.86R4pFgNvcABdrNx6_x_qYpi2aM-Zq43nh_JcfdAXg4"
}

### token check correct
POST http://127.0.0.1:8080/token-check
Content-Type: application/json

{
  "appId": "abc",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjU0NDQ3OTIsIm5iZiI6MTY4OTQ0NDc5MiwiaWF0IjoxNjg5NDQ0NzkyLCJhcHBJZCI6ImFiYyIsImRhdGEiOiInbmFtZSc6J3plbnBrJyJ9.86R4pFgNvcABdrNx6_x_qYpi2aM-Zq43nh_JcfdAXg4"
}

### token parse failure
POST http://127.0.0.1:8080/token-parse
Content-Type: application/json

{
  "appId": "abc",
  "token": "abc"
}

### token parse wrong appId
POST http://127.0.0.1:8080/token-parse
Content-Type: application/json

{
  "appId": "abcd",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjU0NDQ3OTIsIm5iZiI6MTY4OTQ0NDc5MiwiaWF0IjoxNjg5NDQ0NzkyLCJhcHBJZCI6ImFiYyIsImRhdGEiOiInbmFtZSc6J3plbnBrJyJ9.86R4pFgNvcABdrNx6_x_qYpi2aM-Zq43nh_JcfdAXg4"
}

### token parse sucess
POST http://127.0.0.1:8080/token-parse
Content-Type: application/json

{
  "appId": "abc",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjU0NDQ3OTIsIm5iZiI6MTY4OTQ0NDc5MiwiaWF0IjoxNjg5NDQ0NzkyLCJhcHBJZCI6ImFiYyIsImRhdGEiOiInbmFtZSc6J3plbnBrJyJ9.86R4pFgNvcABdrNx6_x_qYpi2aM-Zq43nh_JcfdAXg4"
}
